engines:
  'camunda-bpm':
    rest: http://camunda-platform:8080/engine-rest
    webapps:
      endpoint: http://camunda-platform:8080/camunda
      enabled: true
    name: default
    importEnabled: true
    authentication:
      enabled: true
      user: demo
      password: demo
