engines:
  'camunda-bpm':
    rest: http://camunda-platform-n1:8081/engine-rest
    webapps:
      endpoint: http://camunda-platform-n1:8081/camunda
      enabled: true
    name: default
    importEnabled: true
    authentication:
      enabled: true
      user: demo
      password: demo
